### PR TITLE
chore: reduce imports

### PR DESCRIPTION
**Pull request by semorrison**
Reduce imports.

### CODE REVIEW

**Comment by semorrison** [comment]
@digama0, do you know why `lake exe shake Std` (run from Mathlib) doesn't report this?

**Comment by digama0** [comment]
Uh oh, there was a bug which after fixing is generating loads more shake reports...

**Comment by semorrison** [comment]
Good news! :-)

**Comment by digama0** [comment]
I pushed the results of the shake report to this branch. I'll make a PR separately to mathlib with the noshake.json changes for std, such that running `lake exe shake Std` works as expected. (This is a bit of a layering violation, we should probably upstream `shake` if we want to keep this working.)

**Review by joehendrix — APPROVED** [review]

**Pull request merged**
