### PR TITLE
refactor: Adjust to new termination_by syntax

### PR DESCRIPTION
**Pull request by nomeata**
this makes the necessary changes to compile with the `termination_by`
syntax refactoring in https://github.com/leanprover/lean4/pull/3040.

### CODE REVIEW

**Comment by fgdorais** [comment]
Not sure if the tag `v4.5.0` was appropriate. Please change if necessary.

**Comment by nomeata** [comment]
I guess the draft PR status duplicates the WIP label information?

Anyways, once we know when https://github.com/leanprover/lean4/pull/3040 will land we'll know when to proceed here.

**Comment by nomeata** [comment]
WIP

**Comment by fgdorais** [comment]
Thanks! It's really just to help managing the PR queue, even if the info is duplicated.

**Comment by nomeata** [comment]
Have you considered ignoring draft PRs in the queue?

**Comment by fgdorais** [comment]
I do but it's not that common to use draft PRs on Std. Most people just keep those on their own forks. It only takes a second look for a draft but WIP just takes one look and it's at the same place as all the other useful info.

**Comment by nomeata** [comment]
Got it, will try to remember to WIP my draft PRs!

**Comment by semorrison** [comment]
I'm closing this, as it's already been merged to both `nightly-testing` and `bump/v4.6.0`.

**Pull request closed without merging**
