### PR TITLE
doc: status labels

### LINKED ISSUE #402: Document std4#232
This was a really useful addition which allows any user to update `awaiting-review`, `awaiting-author` and `WIP` labels. Since it's especially useful for first-time contributors, there should be documentation somewhere. Maybe I missed something but I couldn't find it.

### PR DESCRIPTION
**Pull request by fgdorais**
Fixes #402

### CODE REVIEW

**Review by semorrison — APPROVED** [review]

**Review by joehendrix — APPROVED** [review]

**Comment by joehendrix** [comment]
Ironically, you didn't include a label on this PR.  Is there more you wanted to write or is this done?

**Comment by fgdorais** [comment]
lol! I'm loving the irony so I will let it be :)

**Comment by fgdorais** [comment]
I did do two changes though, the rewording of the `proof_wanted` part wasn't actually intended for this PR but I think it's a fine improvement. I'm really busy these days so I'm only doing bits and pieces when I can. Feel free to correct anything I overlooked.

**Comment by fgdorais** [comment]
I could split in two but they are both pretty easy.

**Pull request merged**
