### PR TITLE
feat: Add nix flake

### PR DESCRIPTION
**Pull request by Anderssorby**
Add a nix flake setup for those who use lean through nix. This is a step in my project to integrate lake into nix.

### CODE REVIEW

**Comment by digama0** [comment]
@gebner Can you help test this and set up CI to make sure it works?

**Comment by digama0** [comment]
As things are currently I don't think I can accept this PR because I can't make sure it is working nor keep it up to date. I think nix needs to find a way to do builds which does not involve making all lean 4 projects maintain two independent build pipelines.

**Comment by Anderssorby** [comment]
@digama0 Yes, my project Nix.lean intends to fix that by providing native Nix support to lean which then can be added to lake. I guess we can postpone it until then, but I'm using this update to run Nix.lean (I should probably switch to using lake, but I like using nix so much).

**Comment by joehendrix** [comment]
Closed per discussion above.  Reopen if needed.

**Pull request closed without merging**
