### PR TITLE
chore(Data/List): drop `removeNth`

### PR DESCRIPTION
**Pull request by urkud**
Use `eraseIdx` instead.

### CODE REVIEW

**Comment by urkud** [comment]
Should I add some deprecated aliases?
awaiting-review

**Comment by digama0** [comment]
Yes, for all names that disappear you should have a deprecated alias for it

**Comment by urkud** [comment]
If I use `@[deprecated] alias`, then the aliases will be about `eraseIdx`, not `removeNth`. Should I manually restate lemmas for `removeNth`?

**Comment by digama0** [comment]
That's okay, the two will be defeq anyway and it's better to get the code action.

**Comment by urkud** [comment]
Done

**Comment by urkud** [comment]
awaiting-review

**Review by digama0 — APPROVED** [review]

**Pull request merged**
