### PR TITLE
feat: Eq.ndrec lemma

### PR DESCRIPTION
**Pull request by fgdorais**
Not sure about the name nor where to put this but it is definitely handy to get rid of `▸`:
```lean
example (h : n = m) (x : Fin n) : (Eq.ndrec x h).val = x.val := congr_ndrec ..
```

### CODE REVIEW

**Comment by fgdorais** [comment]
Hm. It doesn't pass the simp test because the lhs head symbol is a variable. Still, it *sometimes* works and it objectively simplifies when it does. Is this worth an exception?

**Comment by digama0** [comment]
> Hm. It doesn't pass the simp test because the lhs head symbol is a variable. Still, it sometimes works and it objectively simplifies when it does. Is this worth an exception?

The reason these are disallowed is not because it doesn't work, but because it's a performance issue - they cannot be meaningfully indexed so they apply literally everywhere. I think there should not be an exception made here since it is a rarely used lemma.

**Comment by fgdorais** [comment]
Interesting idea. How would that work?

**Review by joehendrix — APPROVED** [review]
I don't have any recent experience with dependent congruence elimination, but this seems reasonable to me.

**Comment by fgdorais** [comment]
This lemma could actually be superseded by #465. I'm not sure though.

**Comment by fgdorais** [comment]
False alarm, it's not quite covered by #465.

**Pull request merged**
