### PR TITLE
feat: extCore'

### PR DESCRIPTION
**Pull request by mo271**
Moved from Mathlib.CategoryTheory.Basic in order to be more moveable.

Corresponding mathlib4 pr needed.

### CODE REVIEW

**Comment by mo271** [comment]
Corresponding mathlib4 pr: https://github.com/leanprover-community/mathlib4/pull/5329

**Comment by digama0** [comment]
I don't think this is appropriate for std. Defining a thunk for tagging purposes in mathlib seems just fine to me.

**Comment by mo271** [comment]
see suggestions here: https://github.com/leanprover-community/mathlib4/pull/5157#discussion_r1233705472

**Comment by mo271** [comment]
ok

**Pull request closed without merging**
