### PR TITLE
fix: use `match` with `Decidable` in List instances

### PR DESCRIPTION
**Pull request by collares**
This works around leanprover/lean4#2552; the idea is copied from leanprover-community/mathlib4#7232. Fixes the timeouts described in https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/brute.20force.20calculation.20of.20Bell.2FStirling.20numbers.

### CODE REVIEW

**Comment by kbuzzard** [comment]
Of course the correct question is "why is this happening" :-) If that could be isolated and fixed, this PR wouldn't be needed!

**Comment by collares** [comment]
True! In the meantime, the forall/exists instances in Logic.lean and Data/Option/Basic.lean probably should have the same workaround applied to them too.

**Comment by collares** [comment]
awaiting-review

**Comment by collares** [comment]
If it helps, here's the output of `#reduce decidableBEx` before and after the change.

Before:
```lean
fun p [inst : DecidablePred p] x =>
  rec (isFalse (_ : ∀ (a : ∃ x, x ∈ [] ∧ p x), (fun a => False) a))
    (fun head tail tail_ih =>
      Decidable.rec
        (fun h =>
          Decidable.rec (fun h_1 => isFalse (_ : ∀ (x : ∃ x, x ∈ head :: tail ∧ p x), (fun x => False) x))
            (fun h => isTrue (_ : (fun h₂ => ∃ x, x ∈ head :: tail ∧ p x) h))
            (rec { fst := isFalse (_ : ∀ (a : ∃ x, x ∈ [] ∧ p x), (fun a => False) a), snd := PUnit.unit }
                (fun head tail tail_ih =>
                  {
                    fst :=
                      Decidable.rec
                        (fun h =>
                          Decidable.rec
                            (fun h_1 => isFalse (_ : ∀ (x : ∃ x, x ∈ head :: tail ∧ p x), (fun x => False) x))
                            (fun h => isTrue (_ : (fun h₂ => ∃ x, x ∈ head :: tail ∧ p x) h)) tail_ih.1)
                        (fun h => isTrue (_ : ∃ x, x ∈ head :: tail ∧ p x)) (inst head),
                    snd := { fst := tail_ih, snd := PUnit.unit } })
                tail).1)
        (fun h => isTrue (_ : ∃ x, x ∈ head :: tail ∧ p x)) (inst head))
    x
```

After:
```lean
fun p [inst : DecidablePred p] x =>
  (rec { fst := isFalse (_ : ∀ (a : ∃ x, x ∈ [] ∧ p x), (fun a => False) a), snd := PUnit.unit }
      (fun head tail tail_ih =>
        {
          fst :=
            Decidable.rec
              (fun h =>
                Decidable.rec (fun h_1 => isFalse (_ : ∀ (x : ∃ x, x ∈ head :: tail ∧ p x), (fun x => False) x))
                  (fun h => isTrue (_ : (fun h₂ => ∃ x, x ∈ head :: tail ∧ p x) h)) tail_ih.1)
              (fun h => isTrue (_ : ∃ x, x ∈ head :: tail ∧ p x)) (inst head),
          snd := { fst := tail_ih, snd := PUnit.unit } })
      x).1
```

**Comment by collares** [comment]
(A previous stupid comment of mine was deleted)

**Comment by semorrison** [comment]
This is worse than the issue described in https://github.com/leanprover/lean4/issues/2552: here it's not `cases` that is a problem, but merely `if`.

Would you be able to open a lean4 issue demonstrating this problem? 

Hacky workarounds like these need to be accompanied by links in the source code to the relevant issues, so we can undo them later.

**Comment by collares** [comment]
Thanks for not blindly merging. Turns out I hadn't fully reverted some other changes, and this PR is not helpful for fixing the Zulip issues. Closing.

**Pull request closed without merging**
