### PR TITLE
feat: add Nat.mul_lt_mul₀

### PR DESCRIPTION
**Pull request by sorawee**
This is a Nat variant of
https://leanprover-community.github.io/mathlib4_docs/Mathlib/Algebra/Order/WithZero.html#mul_lt_mul%E2%82%80

### CODE REVIEW

**Comment by sorawee** [comment]
Let me know which naming convention I should follow. There are:

- `Nat.mul_lt_mul`
- `Nat.mul_lt_mul'`
- `mul_lt_mul₀`

and they all use different conventions. Right now I am following `Nat.mul_lt_mul'`.

**Comment by digama0** [comment]
It appears that particular theorem derives from https://github.com/leanprover-community/lean/commit/e865d103751f771e8d2836be4e311fc18c3794a0 : it did have the hypothesis but lost it later.

**Comment by fgdorais** [comment]
Here is a proposal to fix these issues:
```lean
-- formerly: mul_le_mul_of_nonneg_left
protected theorem mul_le_mul_left' {a b c : Nat} : a ≤ b → c * a ≤ c * b := Nat.mul_le_mul_left c

-- formerly: mul_le_mul_of_nonneg_right
protected theorem mul_le_mul_right' {a b c : Nat} : a ≤ b → a * c ≤ b * c := Nat.mul_le_mul_right c

-- formerly: mul_lt_mul, with hypothesis 0 < b weakened to 0 < d
protected theorem mul_lt_mul_of_lt_of_le (hac : a < c) (hbd : b ≤ d) (hd : 0 < d) : a * b < c * d :=
  Nat.lt_of_le_of_lt (Nat.mul_le_mul_left' hbd) (Nat.mul_lt_mul_of_pos_right hac hd)

-- formerly: mul_lt_mul'
protected theorem mul_lt_mul_of_le_of_lt (hac : a ≤ c) (hbd : b < d) (hc : 0 < c) : a * b < c * d :=
  Nat.lt_of_le_of_lt (Nat.mul_le_mul_right' hac) (Nat.mul_lt_mul_of_pos_left hbd hc)

-- formerly: mul_lt_mul₀
protected theorem mul_lt_mul {a b c d : Nat} (hac : a < c) (hbd : b < d) : a * b < c * d :=
  Nat.mul_lt_mul_of_le_of_lt (Nat.le_of_lt hac) hbd (Nat.zero_lt_of_lt hac)
```
These changes don't break anything in Std. I did a rudimentary search through Mathlib and only found a couple of instances of each of the former lemmas.

**Comment by sorawee** [comment]
The proposal looks good to me. Feel free to close this PR if that approach is taken instead.

**Comment by fgdorais** [comment]
Now incorporated in #177 under the name `Nat.mul_lt_mul`.

**Comment by sorawee** [comment]
Nice, and thank you!

**Pull request closed without merging**
