### PR TITLE
feat: S[ubs]tring.{posOf,contains}S[ubs]tr

### PR DESCRIPTION
**Pull request by JamesGallicchio**
Adds functions for finding or checking existence of strings in strings and substrings in substrings and those things in between.

Worst-case `O(nm)` runtime on all new functions, where `n = |s|, m = |pattern|`.

### CODE REVIEW

**Comment by fgdorais** [comment]
#178 now incorporates this PR with worst case O(n+m) runtime on all new functions, where n = |s|, `m = |pattern|.

**Comment by fgdorais** [comment]
I'm marking this as WIP since it's incorporated into #178. (At least partly, I think I modified some bits.) If you want to close it, that's fine too. Remember that you can always comment on #178 if the edits I made are inappropriate for your needs.

**Comment by semorrison** [comment]
I think it's fine to just close. @JamesGallicchio is probably happy with the outcome of a faster implementation, and can take the credit for nerd-snipping @fgdorais into making the #178 PR. :-) Of course can be re-opened etc if I've missed something.

**Comment by JamesGallicchio** [comment]
At first I was thinking the naive implementation should be kept around as the reference implementation against which we verify correctness, but then I decided that I do not care about the functional correctness of string matching :-)

**Comment by digama0** [comment]
the naive implementation isn't naive enough to be usable as a model for functional correctness. I would prefer `<:+:` on the underlying lists for the model.

**Pull request closed without merging**
