### PR TITLE
chore: upstream split_ifs

### PR DESCRIPTION
**Pull request by semorrison**

### CODE REVIEW

**Comment by digama0** [comment]
This one seems like big sadness to me, why can't we use `split` instead? Have we given up on progressing https://github.com/leanprover/lean4/issues/2414 or is the issue something else?

**Comment by semorrison** [comment]
@digama0 my main complaint is lack of `split with h`.

**Comment by digama0** [comment]
Is that a feature request I hear?

**Comment by semorrison** [comment]
I'm going to close this now, let's see if we can work on `split` instead.

**Pull request closed without merging**
